### ISSUE TITLE
ça marche pas

### ISSUE THREAD

**Issue by frezae** [grena/starsector_french_translation_mod#1]
bonjour j'ai installer le mod mais il marche pas je voulais savoir si vous pouviez Maider merci

**Comment by grena** [comment]
Bonjour @frezae ,

A quelle étape de l'installation cela ne marche pas ? Je vais tenter de le réinstaller prochainement pour voir si je rencontre des problèmes aussi.

**Comment by frezae** [comment]
bonjour @grena  
j'ai installer le mode  je voix bien que je lai j'ai la bonne version est quand je lance le jeux ça reste en anglai 
est je nait pas d'autre mode

**Comment by grena** [comment]
D'accord, dans ce cas le mod a bien été installé. :+1: 

Tout n'a pas encore été traduit, **c'est pour cela que certains éléments apparaissent encore en anglais dans le jeu**, car il y a énormément de texte à traduire.

L'idée c'est que la communauté FR participe à la traduction du jeu.

Si vous avez le temps et l'envie, n'hésitez pas à contribuer, voici le genre de fichier à éditer : https://github.com/grena/starsector_french_translation_mod/blob/main/data/strings/descriptions.csv

C'est assez simple, mais très chronophage :smile:

**Comment by makrinthor** [comment]
je vais y jeter un oeil afin de pouvoir aider un peu

@Frezae, vu ton orthographe et ta grammaire, cela ne sert a rien de traduire le jeu :)

@Grena: j'ai vu pour un autre jueu qu'il existe aussi des sites specialement dédiés à la traduction

**Comment by grena** [comment]
Oui si tu arrives à retrouver le site/outil qu'ils utilisaient, je suis curieux :)
Mais globalement les sites type https://poeditor.com/ ou https://crowdin.com/ sont en général payant, de plus Starsector utilise à la fois du `.json` et du `.csv`, donc à voir si ces sites gèrent ça aussi.

En tout cas merci pour votre intérêt sur le mod !
