### ISSUE TITLE
JSONObject["icon"] not found.

### ISSUE THREAD

**Issue by Pepersil** [grena/starsector_french_translation_mod#3]
j'ai cette erreur qui s'affiche quand je lance le jeuxcc avec le mods quelquun peux m'aider ?

**Comment by grena** [comment]
Salut @Pepersil , merci pour ton retour, je regarde ça demain (je n'ai pas le jeu sous la main) et je reviens vers toi !

**Comment by Pepersil** [comment]
@grena merci j'attend ton aide ^^

**Comment by grena** [comment]
Salut @Pepersil , tu peux de nouveau télécharger le mod : https://github.com/grena/starsector_french_translation_mod/archive/refs/heads/main.zip

Ca devrait fonctionner maintenant.

**Comment by Dompteure** [comment]
Salut déjà merci pour ce boulot mais lorsque je l'installe et l'active quand je lance le jeu il est toujours en anglais tu saurais pourquoi ?

**Comment by grena** [comment]
Bonjour @Dompteure ,

Je t'invite à lire ma réponse ici : https://github.com/grena/starsector_french_translation_mod/issues/1#issuecomment-1134750434
